remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: Manuela Gutierrez 
submodulo: Nuevas tecnologías1
periodo: 2023-2
url_foto: https://firebasestorage.googleapis.com/v0/b/manu-167d8.appspot.com/o/IMG_1403.jpg?alt=media&token=b6bea4ab-9371-48fb-8ee0-920ac4c9ef5d&_gl=1*3fv9mg*_ga*NDY5NTY0MTU5LjE2OTY2OTM4MzE.*_ga_CW55HF8NVT*MTY5NjY5Mzg5MS4xLjEuMTY5NjY5NDQzNi40MC4wLjA.

